<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <Version>1.1.2</Version>
    <AssemblyVersion>1.1.2.0</AssemblyVersion>
    <FileVersion>1.1.2.0</FileVersion>
    <InformationalVersion>1.1.2</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.*" />
    <PackageReference Include="Avalonia.AvaloniaEdit" Version="11.3.0" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="11.*" />
    <PackageReference Include="Avalonia.Desktop" Version="11.*" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.*" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.*" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.*" Condition="'$(Configuration)' == 'Debug'" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="../../resources/images/logoPseudoCode.png" Link="Assets/logoPseudoCode.png" />
    <AvaloniaResource Include="../../resources/images/iconKityDev.png" Link="Assets/iconKityDev.png" />
    <AvaloniaResource Include="../../resources/images/LogoKityDev.png" Link="Assets/LogoKityDev.png" />
    <AvaloniaResource Include="../../resources/images/KityDev/*.png" Link="Assets/KityDev/%(Filename)%(Extension)" />
    <AvaloniaResource Include="../../docs/ayuda.md" Link="Docs/ayuda.md" />
    <AvaloniaResource Include="../../docs/pseudolenguaje.md" Link="Docs/pseudolenguaje.md" />
    <AvaloniaResource Include="../../docs/configuracion-json.md" Link="Docs/configuracion-json.md" />
    <AvaloniaResource Include="../../CHANGELOG.md" Link="Docs/CHANGELOG.md" />
    <Content Include="settings/**/*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
